//! PF Firewall Guard — blocage réseau kernel-level via pf (packet filter).
//!
//! Ce module bloque le trafic réseau sortant de l'agent IA au niveau kernel.
//! pf filtre par UID (utilisateur macOS dédié), ce qui est incontournable
//! par le userspace — ni Node.js, ni curl, ni nc ne peuvent le contourner.
//!
//! Architecture :
//! - `PfRuleGenerator` (pure) — génère les règles pf
//! - `PfController` (I/O) — exécute pfctl
//! - `DomainResolver` — résout les domaines en IPs
//! - `PfGuard` — implémente le Guard trait

use crate::config::{AppConfig, PfGuardConfig};
use crate::types::{Guard, GuardStatus, SecurityEvent};
use chrono::Utc;
use std::net::IpAddr;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, RwLock};
use std::time::Instant;
use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;

// ---------------------------------------------------------------------------
// ResolvedDestination — résultat de résolution DNS
// ---------------------------------------------------------------------------

/// Destination résolue avec ses IPs et son timestamp de résolution.
pub struct ResolvedDestination {
    /// Domaine ou IP original (ex: "api.openai.com")
    pub original: String,
    /// IPs résolues
    pub ips: Vec<IpAddr>,
    /// Moment de la résolution
    pub resolved_at: Instant,
}

// ---------------------------------------------------------------------------
// PfRuleGenerator — logique pure de génération de règles pf
// ---------------------------------------------------------------------------

/// Génère les règles d'ancre pf à partir de la config et des IPs résolues.
pub struct PfRuleGenerator {
    agent_username: String,
    #[allow(dead_code)]
    anchor_name: String,
}

impl PfRuleGenerator {
    /// Crée un nouveau générateur de règles pf.
    pub fn new(agent_username: &str, anchor_name: &str) -> Self {
        Self {
            agent_username: agent_username.to_string(),
            anchor_name: anchor_name.to_string(),
        }
    }

    /// Génère les règles d'ancre pf complètes.
    ///
    /// Structure :
    /// 1. Table <counterclaw_allowed> avec les IPs whitelistées (si non vide)
    /// 2. pass lo0 (localhost toujours autorisé)
    /// 3. pass DNS (résolution toujours autorisée)
    /// 4. pass vers table whitelistée (si non vide)
    /// 5. block tout le reste pour cet utilisateur
    pub fn generate_anchor_rules(&self, resolved: &[ResolvedDestination]) -> String {
        let mut rules = String::new();
        rules.push_str("# Auto-generated by CounterClaw — do not edit\n");

        let all_ips = Self::generate_table_ips(resolved);

        // Table de IPs autorisées (seulement si non vide)
        if !all_ips.is_empty() {
            let ip_list: Vec<String> = all_ips.iter().map(|ip| ip.to_string()).collect();
            rules.push_str(&format!(
                "table <counterclaw_allowed> {{ {} }}\n\n",
                ip_list.join(", ")
            ));
        }

        // Règle 1 : localhost toujours autorisé
        rules.push_str(&format!(
            "pass out quick on lo0 user {}\n",
            self.agent_username
        ));

        // Règle 2 : DNS toujours autorisé
        rules.push_str(&format!(
            "pass out quick proto udp from any to any port 53 user {}\n",
            self.agent_username
        ));

        // Règle 3 : trafic vers IPs whitelistées (si table non vide)
        if !all_ips.is_empty() {
            rules.push_str(&format!(
                "pass out quick proto {{ tcp udp }} from any to <counterclaw_allowed> user {}\n",
                self.agent_username
            ));
        }

        // Règle 4 : bloquer tout le reste
        rules.push_str(&format!(
            "block drop out log proto {{ tcp udp }} user {}\n",
            self.agent_username
        ));

        rules
    }

    /// Collecte et déduplique toutes les IPs de toutes les destinations résolues.
    pub fn generate_table_ips(resolved: &[ResolvedDestination]) -> Vec<IpAddr> {
        let mut seen = std::collections::HashSet::new();
        let mut ips = Vec::new();
        for dest in resolved {
            for ip in &dest.ips {
                if seen.insert(*ip) {
                    ips.push(*ip);
                }
            }
        }
        ips
    }

    /// Valide un nom d'utilisateur (uniquement [a-zA-Z0-9_-]).
    pub fn validate_username(username: &str) -> Result<(), String> {
        if username.is_empty() {
            return Err("Username cannot be empty".to_string());
        }
        if !username
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
        {
            return Err(format!(
                "Username '{}' contains invalid characters (only [a-zA-Z0-9_-] allowed)",
                username
            ));
        }
        Ok(())
    }

    /// Vérifie si une adresse est localhost.
    pub fn is_localhost(addr: &str) -> bool {
        matches!(addr, "127.0.0.1" | "::1" | "localhost")
    }
}

// ---------------------------------------------------------------------------
// PfController — couche I/O wrappant pfctl
// ---------------------------------------------------------------------------

/// Wrapper autour de `pfctl` pour gérer les règles pf.
///
/// Utilise `tokio::process::Command` pour les opérations async (même pattern
/// que lsof dans NetGuard). Les méthodes `build_*` retournent les commandes
/// sans les exécuter (testable en isolation).
pub struct PfController {
    anchor_name: String,
}

impl PfController {
    /// Crée un nouveau controller pour l'ancre pf donnée.
    pub fn new(anchor_name: &str) -> Self {
        Self {
            anchor_name: anchor_name.to_string(),
        }
    }

    /// Construit la commande pour installer des règles dans l'ancre.
    /// `pfctl -a <anchor> -f -` (lecture depuis stdin)
    pub fn build_install_command(&self, _rules: &str) -> (String, Vec<String>) {
        (
            "pfctl".to_string(),
            vec![
                "-a".to_string(),
                self.anchor_name.clone(),
                "-f".to_string(),
                "-".to_string(),
            ],
        )
    }

    /// Construit la commande pour vider les règles de l'ancre.
    /// `pfctl -a <anchor> -F all`
    pub fn build_flush_command(&self) -> (String, Vec<String>) {
        (
            "pfctl".to_string(),
            vec![
                "-a".to_string(),
                self.anchor_name.clone(),
                "-F".to_string(),
                "all".to_string(),
            ],
        )
    }

    /// Construit la commande pour activer pf.
    /// `pfctl -E` (ref-counted, safe même si pf déjà actif)
    pub fn build_enable_command(&self) -> (String, Vec<String>) {
        ("pfctl".to_string(), vec!["-E".to_string()])
    }

    /// Construit la commande pour désactiver pf.
    /// `pfctl -d`
    #[allow(dead_code)]
    pub fn build_disable_command(&self) -> (String, Vec<String>) {
        ("pfctl".to_string(), vec!["-d".to_string()])
    }

    /// Construit la commande pour remplacer les IPs dans une table pf.
    /// `pfctl -a <anchor> -t <table> -T replace <ip1> <ip2> ...`
    pub fn build_table_replace_command(
        &self,
        table_name: &str,
        ips: &[IpAddr],
    ) -> (String, Vec<String>) {
        let mut args = vec![
            "-a".to_string(),
            self.anchor_name.clone(),
            "-t".to_string(),
            table_name.to_string(),
            "-T".to_string(),
            "replace".to_string(),
        ];
        for ip in ips {
            args.push(ip.to_string());
        }
        ("pfctl".to_string(), args)
    }

    /// Vérifie si le processus courant tourne en root (UID 0).
    pub fn is_root() -> bool {
        #[cfg(unix)]
        {
            // Use sysinfo to check if current user is root
            // Alternative: parse /etc/passwd or use id command
            // Simplest portable approach: check EUID via std
            std::process::Command::new("id")
                .arg("-u")
                .output()
                .ok()
                .and_then(|o| String::from_utf8(o.stdout).ok())
                .map(|s| s.trim() == "0")
                .unwrap_or(false)
        }
        #[cfg(not(unix))]
        {
            false
        }
    }

    /// Installe les règles pf dans l'ancre via pfctl.
    #[allow(dead_code)]
    pub async fn install_anchor(&self, rules: &str) -> anyhow::Result<()> {
        let (program, args) = self.build_install_command(rules);
        let output = tokio::process::Command::new(&program)
            .args(&args)
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .spawn()?
            .wait_with_output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("pfctl install failed: {}", stderr);
        }
        Ok(())
    }

    /// Vide les règles de l'ancre.
    #[allow(dead_code)]
    pub async fn flush_anchor(&self) -> anyhow::Result<()> {
        let (program, args) = self.build_flush_command();
        let output = tokio::process::Command::new(&program)
            .args(&args)
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("pfctl flush failed: {}", stderr);
        }
        Ok(())
    }

    /// Met à jour les IPs d'une table pf via pfctl.
    #[allow(dead_code)]
    pub async fn update_table(&self, table_name: &str, ips: &[IpAddr]) -> anyhow::Result<()> {
        let (program, args) = self.build_table_replace_command(table_name, ips);
        let output = tokio::process::Command::new(&program)
            .args(&args)
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .output()
            .await?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("pfctl table replace failed: {}", stderr);
        }
        Ok(())
    }

    /// Active pf (ref-counted, safe même si déjà actif).
    #[allow(dead_code)]
    pub async fn enable_pf(&self) -> anyhow::Result<()> {
        let (program, args) = self.build_enable_command();
        let output = tokio::process::Command::new(&program)
            .args(&args)
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .output()
            .await?;

        // pfctl -E can exit with non-zero even on success (e.g., "pf already enabled")
        // We only fail if stderr contains "Permission denied" or similar
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            if stderr.contains("Permission denied") {
                anyhow::bail!("pfctl -E failed (permission denied): {}", stderr);
            }
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// DomainResolver — résolution DNS async
// ---------------------------------------------------------------------------

/// Résout les domaines en IPs via `tokio::net::lookup_host()`.
pub struct DomainResolver;

impl DomainResolver {
    /// Résout tous les domaines en IPs. Les IPs directes sont passées telles quelles.
    /// Les domaines non-résolvables retournent une entrée avec un vecteur d'IPs vide.
    pub async fn resolve_all(domains: &[String]) -> Vec<ResolvedDestination> {
        let mut results = Vec::with_capacity(domains.len());

        for domain in domains {
            let resolved_at = Instant::now();

            // Si c'est déjà une IP, pas besoin de DNS
            if let Some(ip) = Self::parse_ip_direct(domain) {
                results.push(ResolvedDestination {
                    original: domain.clone(),
                    ips: vec![ip],
                    resolved_at,
                });
                continue;
            }

            // Résolution DNS async
            // lookup_host attend "host:port", on utilise le port 0
            let lookup_addr = format!("{}:0", domain);
            let ips = match tokio::net::lookup_host(lookup_addr.as_str()).await {
                Ok(addrs) => addrs.map(|a| a.ip()).collect(),
                Err(_) => Vec::new(),
            };
            results.push(ResolvedDestination {
                original: domain.clone(),
                ips,
                resolved_at,
            });
        }

        results
    }

    /// Parse une chaîne comme IP directe. Retourne None si c'est un domaine.
    pub fn parse_ip_direct(addr: &str) -> Option<IpAddr> {
        addr.parse::<IpAddr>().ok()
    }
}

// ---------------------------------------------------------------------------
// PfGuard — implémentation du Guard trait
// ---------------------------------------------------------------------------

/// PF Firewall Guard : bloque le trafic réseau sortant au niveau kernel
/// pour un utilisateur macOS dédié via pf (packet filter).
///
/// Dégradation gracieuse :
/// - Pas root → mode audit-only (log, pas de pfctl)
/// - Linux → log info + return Ok (pf n'existe pas)
/// - Utilisateur inexistant → Critical event au start
pub struct PfGuard {
    config: PfGuardConfig,
    running: Arc<AtomicBool>,
    events_total: Arc<AtomicU64>,
    events_blocked: Arc<AtomicU64>,
    start_time: Arc<std::sync::Mutex<Option<chrono::DateTime<Utc>>>>,
    cancel_token: CancellationToken,
    task_handle: Arc<tokio::sync::Mutex<Option<tokio::task::JoinHandle<()>>>>,
    #[allow(dead_code)]
    app_config: Arc<RwLock<AppConfig>>,
}

impl PfGuard {
    /// Crée un nouveau PfGuard à partir de la configuration.
    pub fn new(config: &PfGuardConfig, app_config: Arc<RwLock<AppConfig>>) -> Self {
        Self {
            config: config.clone(),
            running: Arc::new(AtomicBool::new(false)),
            events_total: Arc::new(AtomicU64::new(0)),
            events_blocked: Arc::new(AtomicU64::new(0)),
            start_time: Arc::new(std::sync::Mutex::new(None)),
            cancel_token: CancellationToken::new(),
            task_handle: Arc::new(tokio::sync::Mutex::new(None)),
            app_config,
        }
    }
}

#[async_trait::async_trait]
impl Guard for PfGuard {
    fn name(&self) -> &str {
        "pf_guard"
    }

    async fn start(&self, alert_tx: mpsc::Sender<SecurityEvent>) -> anyhow::Result<()> {
        self.running.store(true, Ordering::SeqCst);
        *self.start_time.lock().expect("lock poisoned") = Some(Utc::now());

        if !self.config.enabled {
            tracing::info!("PF Guard disabled in config — skipping");
            return Ok(());
        }

        // Plateforme check : pf n'existe que sur macOS/BSD
        #[cfg(not(target_os = "macos"))]
        {
            tracing::info!("PF Guard: pf not available on this platform — audit-only mode");
            return Ok(());
        }

        // Root check : pf nécessite root pour l'enforcement
        #[cfg(target_os = "macos")]
        {
            let is_root = PfController::is_root();

            if !is_root {
                tracing::warn!(
                    "PF Guard: not running as root — audit-only mode (no pfctl enforcement)"
                );

                // En mode audit, on lance quand même le background task pour
                // logger ce qui SERAIT bloqué, mais sans pfctl
                let cancel = self.cancel_token.clone();
                let config = self.config.clone();
                let events_total = Arc::clone(&self.events_total);
                let app_config = Arc::clone(&self.app_config);

                let handle = tokio::spawn(async move {
                    Self::run_audit_loop(cancel, config, events_total, alert_tx, app_config).await;
                });

                *self.task_handle.lock().await = Some(handle);
                return Ok(());
            }

            // Root mode — install pf rules
            let controller = PfController::new(&self.config.anchor_name);
            let generator =
                PfRuleGenerator::new(&self.config.agent_username, &self.config.anchor_name);

            // Résoudre les domaines
            let resolved = DomainResolver::resolve_all(&self.config.allowed_destinations).await;

            // Générer et installer les règles
            let rules = generator.generate_anchor_rules(&resolved);
            if let Err(e) = controller.enable_pf().await {
                tracing::warn!("Failed to enable pf: {} (may already be enabled)", e);
            }
            if let Err(e) = controller.install_anchor(&rules).await {
                tracing::error!("Failed to install pf anchor rules: {}", e);
                return Ok(());
            }

            tracing::info!(
                "PF Guard active: blocking all egress for user '{}' except {} destinations",
                self.config.agent_username,
                self.config.allowed_destinations.len()
            );

            // Lancer le background task pour hot-reload et DNS refresh
            let cancel = self.cancel_token.clone();
            let config = self.config.clone();
            let events_total = Arc::clone(&self.events_total);
            let app_config_clone = Arc::clone(&self.app_config);

            let handle = tokio::spawn(async move {
                Self::run_enforcement_loop(
                    cancel,
                    config,
                    events_total,
                    alert_tx,
                    app_config_clone,
                )
                .await;
            });

            *self.task_handle.lock().await = Some(handle);
        }

        Ok(())
    }

    async fn stop(&self) -> anyhow::Result<()> {
        self.cancel_token.cancel();

        if let Some(handle) = self.task_handle.lock().await.take() {
            handle.abort();
            let _ = handle.await;
        }

        self.running.store(false, Ordering::SeqCst);

        // Cleanup: flush anchor rules if we were running as root
        #[cfg(target_os = "macos")]
        if self.config.enabled && PfController::is_root() {
            let controller = PfController::new(&self.config.anchor_name);
            if let Err(e) = controller.flush_anchor().await {
                tracing::warn!("Failed to flush pf anchor on stop: {}", e);
            } else {
                tracing::info!("PF Guard: anchor rules flushed");
            }
        }

        Ok(())
    }

    fn status(&self) -> GuardStatus {
        let start = self
            .start_time
            .lock()
            .expect("lock poisoned")
            .unwrap_or_else(Utc::now);
        let uptime = Utc::now() - start;
        GuardStatus {
            running: self.running.load(Ordering::SeqCst),
            events_total: self.events_total.load(Ordering::SeqCst),
            events_blocked: self.events_blocked.load(Ordering::SeqCst),
            last_event: None,
            uptime,
        }
    }
}

impl PfGuard {
    /// Boucle audit-only : log ce qui serait bloqué sans activer pf.
    async fn run_audit_loop(
        cancel: CancellationToken,
        config: PfGuardConfig,
        _events_total: Arc<AtomicU64>,
        _alert_tx: mpsc::Sender<SecurityEvent>,
        _app_config: Arc<RwLock<AppConfig>>,
    ) {
        let refresh_interval = std::time::Duration::from_secs(config.dns_refresh_seconds);

        loop {
            tokio::select! {
                _ = cancel.cancelled() => {
                    tracing::info!("PF Guard audit loop shutting down");
                    break;
                }
                _ = tokio::time::sleep(refresh_interval) => {
                    // In audit mode, periodically re-resolve to log the state
                    tracing::debug!("PF Guard audit: would refresh DNS for {} destinations",
                        config.allowed_destinations.len());
                }
            }
        }
    }

    /// Boucle d'enforcement : DNS refresh périodique et hot-reload whitelist.
    #[allow(dead_code)]
    async fn run_enforcement_loop(
        cancel: CancellationToken,
        config: PfGuardConfig,
        _events_total: Arc<AtomicU64>,
        _alert_tx: mpsc::Sender<SecurityEvent>,
        app_config: Arc<RwLock<AppConfig>>,
    ) {
        let refresh_interval = std::time::Duration::from_secs(config.dns_refresh_seconds);
        let controller = PfController::new(&config.anchor_name);
        let generator = PfRuleGenerator::new(&config.agent_username, &config.anchor_name);
        let mut last_destinations = config.allowed_destinations.clone();

        loop {
            tokio::select! {
                _ = cancel.cancelled() => {
                    tracing::info!("PF Guard enforcement loop shutting down");
                    break;
                }
                _ = tokio::time::sleep(refresh_interval) => {
                    // Check for config changes (hot-reload)
                    let current_destinations = {
                        let cfg = app_config.read().expect("config read lock");
                        cfg.pf_guard.allowed_destinations.clone()
                    };

                    let destinations_changed = current_destinations != last_destinations;
                    if destinations_changed {
                        tracing::info!("PF Guard: whitelist changed, updating rules");
                        last_destinations = current_destinations.clone();
                    }

                    // Re-resolve DNS (either refresh cycle or whitelist changed)
                    let resolved = DomainResolver::resolve_all(&current_destinations).await;
                    let rules = generator.generate_anchor_rules(&resolved);

                    if let Err(e) = controller.install_anchor(&rules).await {
                        tracing::error!("Failed to update pf rules: {}", e);
                    } else {
                        tracing::debug!("PF Guard: rules refreshed ({} destinations)",
                            current_destinations.len());
                    }
                }
            }
        }
    }
}
